### ISSUE TITLE
Add universal template filter for date formatting

### ISSUE THREAD

**Issue by chantastic** [LunchDevCommunity/community-calendar#12]
I'd love to show formatted dates on both the index and event pages.
I suspect that eleventy's [universal template filters](https://www.11ty.dev/docs/filters/#universal-filters) are the way to go.

Steps:
* Decide on human readable date format
* implement universal template filter in `.elevent.js`
* update `homepage` and `event` templates

**Comment by BenDMyers** [comment]
I love this! Would you be able to give a sense of what you'd expect the API for using this filter to be?

**Comment by chantastic** [comment]
i like the pipe style that seems popular eleventy (at least in nunjucks).

i think this and the youtube one could be fun on a lunch sesh.

any thoughts on readable date format?
i kinda like `Jan 9, 2021`
