### ISSUE TITLE
add netlify redirects for channel-specific discord invites

### ISSUE THREAD

**Issue by chantastic** [LunchDevCommunity/community-calendar#24]
i think it could be useful to create domain redirects for a handful of channel-specific invites (say `live-events`, `new-episode-party`, etc).

right now i'm thinking those could map to channels names but i could absolutely be convinced otherwise.

**Comment by BenDMyers** [comment]
Oooh, so we could send someone a link to https://events.lunch.dev/new-episode-party, and it would take them directly to the `#new-episode-party` channel? That'd be super neat!

**Comment by chantastic** [comment]
i'm going to close this, now that i'm learning how Community Servers work.

Community Servers have "welcome screens" that provide jumping off points to featured channels, making these links less important.

BUT i'm sure we'll come up with something fun for these redirects :)
