### ISSUE TITLE
add .ics calendar (maybe even others)

### ISSUE THREAD

**Issue by chantastic** [LunchDevCommunity/community-calendar#25]
this npm package looks like the one to do it: https://www.npmjs.com/package/ics

**Comment by roman-bytes** [comment]
I wouldn't mind looking into this one! It would be nice to have some sort of add to my calendar option. Will have to get a list of some common calendars people use. Right now I can just think of

- iCal
- Google Calendar
- Outlook

**Comment by chantastic** [comment]
@roman-bytes YES! So excited you're on this.

this issue was started from this twitter thread: https://mobile.twitter.com/lachlanjc/status/1349974552462417920
Lachlan suggested this package in that conversation: https://www.npmjs.com/package/calendar-link

looks like their sample code covers all of the calendar tools you enumerated:

```js
// Usage with Node.js
const { google, outlook, office365, yahoo, ics } = require("calendar-link");

// Usage with TypeScript or ES6
import { google, outlook, office365, yahoo, ics } from "calendar-link";

// Set event as an object
const event = {
  title: "My birthday party",
  description: "Be there!",
  start: "2019-12-29 18:00:00 +0100",
  duration: [3, "hour"],
};

// Then fetch the link
google(event); // https://calendar.google.com/calendar/render...
outlook(event); // https://outlook.live.com/owa/...
office365(event); // https://outlook.office.com/owa/...
yahoo(event); // https://calendar.yahoo.com/?v=60&title=...
ics(event); // standard ICS file based on https://icalendar.org
```

**Comment by chantastic** [comment]
@roman-bytes hmu if you need a hand or if you think this would make for a valuable lunch session for others.
