### ISSUE TITLE
Homepage event preview markup

### ISSUE THREAD

**Issue by BenDMyers** [LunchDevCommunity/community-calendar#4]
Right now, the homepage contains two unordered lists with links out to other events.

We'll want to move towards including more information, probably in a cardlike treatment. Each card will need:

- The event title, displayed prominently
- The event date and duration
- A brief excerpt or description about the event
- A link to the event's page

This should all use appropriate semantic markup. The card's container, for instance, should probably be an `<article>`, since the preview represents a single, standalone entity like that.

Don't worry about styles quite yet — that can be handled down the road, and more holistically with the rest of the site. We'll likely have a group session for styles anyways.

**Comment by michaelgee22** [comment]
I'm going to take a swing at this one to finally contribute :)

**Comment by BenDMyers** [comment]
Thank you, @michaelgee22! Please reach out if you need any help!
