### ISSUE TITLE
Add `location` and `url` to generated events

### ISSUE THREAD

**Issue by chantastic** [LunchDevCommunity/community-calendar#43]
This is a follow-up to @roman-bytes's great work on #25

I'd like to add two fields: `url` and `location`

Once #42 is merged — which sets up a simpler Discord invite link — we can update `url` to be `https://events.lunch.dev/discord` and the location to be a more human readable `Lunch Dev Community Discord at events.lunch.dev`.

Thoughts?

**Comment by roman-bytes** [comment]
I was wondering about this when I was working on the add to calendar, having the discord link in the actual calendar would be super helpful.

The npm package we are using looks to have this option so it will be an easy add. 👍

**Comment by chantastic** [comment]
awesome! any chance you want to take it after #42 gets merged?

**Comment by roman-bytes** [comment]
Sure I can tackle it!
