### ISSUE TITLE
Create a /contributors page

### ISSUE THREAD

**Issue by BenDMyers** [LunchDevCommunity/community-calendar#55]
We added the `all-contributors` bot in #48. This means we can now recognize anyone who contributes in any way to the calendar or its events! 🎉

We can do one better, though. We can use the `contributors` field in the new `.all-contributorsrc` to populate a page on the site itself.

@chantastic and I think this would be a fun lunch session to explore [global data in Eleventy](https://www.11ty.dev/docs/data-global/).

**Comment by chantastic** [comment]
YES! this is awesome @BenDMyers thanks for taking the time and care to get all existing contributors in!

Can't wait for this session?
Did you want to lead it? If so, let's get a date on the calendar for next week! 🥳
