### ISSUE TITLE
No link to the GitHub repo on website homepage

### ISSUE THREAD

**Issue by ajcwebdev** [LunchDevCommunity/community-calendar#94]
When visiting individual event pages there is a helpful link to the GitHub repo, but just from the home page it's not clear where to go if you wanted to find other places connected to events.lunch.dev. Would be useful to pop in links to the Discord as well.

**Comment by BenDMyers** [comment]
This was technically resolved with #95, which added a page footer. However, I don't know if we want to explore any ways to make this link more prominent, since today you have to scroll through all past events to get to the footer.

@ajcwebdev @chantastic Thoughts?

**Comment by chantastic** [comment]
@BenDMyers this is a really good question. Here are two immediate options that come to mind:

1. make the footer sticky. negative: this is fairly uncommon for public pages. positive: always easy to get to.

2. reduce the quantity of previous events we show.

we've talked in other threads about ways to achieve #2

- Filter out events without a recorded artifact
- Present previous events in a smaller way, stylistically. possibly list
- Collapse events past a date horizon behind "More past events…" link

I like the idea of fleshing out #2

Any other considerations we should make?
