### ISSUE TITLE
Local Development becoming slow

### ISSUE THREAD

**Issue by michaelgee22** [LunchDevCommunity/community-calendar#96]
During recent development, I noticed that local development seems to be slowing down more and more due to more events being added to the project.

Each minor CSS change would take a few seconds to update the project and became a bit tedious. I am assuming it will only get worse with more events being added.

**Comment by chantastic** [comment]
looks like this might be an issue worth tracking: https://github.com/11ty/eleventy/issues/108

seems like they don't have built-in for this yet.

i'm interested to see where we might be bogging down our builds and how we could improve that. i imagine that preemptive logging isn't helping us much. but that's just a hunch

**Comment by chantastic** [comment]
@michaelgee22 in #100 i have removed the `event | log` statements and it speeds local development up considerably. once we've merged that, let me know if things are still slow for you

**Comment by chantastic** [comment]
Closing this for now. I think #100 fixed it
